### ISSUE TITLE
Grid내에 컬럼데이터 확인 문의

### ISSUE THREAD

**Issue by ChoiManKi** [naver/guitar#320]
안녕하세요. 
이번에 자동화테스트 구축하면서 GUITAR 를 알게 되었습니다.
무엇보다 스크립트를 몰라도 사용할 수 있어서 회사솔루션테스트에 맞으면 바로 정착시킬려고 합니다.
지금 예제로 이리저리 해보고 있는데, 저같은 상황은 없어서 이렇게 문의글을 남깁니다~_~
제가 하고자 하는 테스트는 버튼에 추가된 기능을 테스트하는 것입니다.

1번 그림을 보시면, grid1.setCellData(0,2,"제주도"); 버튼을 클릭하면 
grid1 에 0,2 부분이 서울 -> 제주도로 데이터가 변경되는 것을 확인하는 샘플화면입니다.

2번 그림에 예제로 작성을 했습니다.
근데 grid1 에 0,2 부분에 제주도가 맞는지 확인하라는 스크립트를 짤려 하는데, 잘모르겠습니다...
버튼위치나 이런것이 아닌, 그리드내에 컬럼데이터가 비교대상이어야 하는데, 검색을 해봐도 못찾겠습니다;

![1](https://cloud.githubusercontent.com/assets/24645147/21303264/8391a104-c600-11e6-9070-6a3089c055be.png)

![2](https://cloud.githubusercontent.com/assets/24645147/21303266/8ae440f6-c600-11e6-989c-9f49f44ed6d4.png)

**Comment by ssmmhh** [comment]
아래와 같이 작성하시면 되됩니다.

제주도 버튼 클릭한다.
컬럼4-제주도 확인한다.


컬럼4-제주도 이미지는 제주도로 변경된 이미지를 캡쳐하시면 되는데, 하실때 하단에 "인천"까지 약간 포함되도록 캡쳐해 주시면 인천위에 제주가 변경된것을 확인하실수 있습니다.
단순하게 "제주" 만 변경된것을 캡쳐해도 되지만, 이럴 경우 원하는 셀이 아닐수 있음으로 인근의 다른 부분까지 살짝 끼워 넣어 주시면 인천 위에 제주가 있다는것을 확인하실수 있습니다.


혹은 좀더 명확하게 하시려면 "부분대상작업" 명령을 사용하시면 됩니다.

우선 "가" 열 제목을  확인한뒤 해당 부근의 우측 특정 영역좌표를 지정해서 그곳에서만 제주 이미지를 찾도록 할수도 있습니다. (27_부분대상작업 샘플을 참고하시면 됩니다.)

**Comment by ChoiManKi** [comment]
빠르고 자세한 답변감사드립니다!
첫번째 방법으로 확인했는데, 잘되네요~!
두번째 방법 부분대상작업은 첫번째 방법보다 약간 어렵지만, 이것도 잘되네요~ㅎ
방금 사수인 차장님에게 보고드렸고, 
몇개 더 예제샘플 자동화해서 GUITAR 에 적용해보고 괜찮으면 바로 팀장님에게 보고하기로 했습니다.
GUITAR 최고인 것 같습니다! 감사합니다~!^^*
