### ISSUE TITLE
FIREFOX, CHROME, OPERA에서 주소창 찾기 문의

### ISSUE THREAD

**Issue by ChoiManKi** [naver/guitar#345]
안녕하세요~
새로운 문의를 드립니다..ㅠ_ㅠ
멀티브라우저를 테스트해야해서 
https://github.com/naver/guitar/issues/96 를 참조해서 새롭게 이미지를 캡처하고 있었습니다.

파이어폭스는 bin폴더와 유사하게 되어있어서 제대로 새로운 이미지로 교체했는데, 
문제는 크롬과 오페라 브라우저였습니다.

DONE 같은경우 비슷하게 생겨서 쉽게 해결을 했는데, 문제는 ADDRESS 부분이었습니다.

현재 bin폴더입니다.
![1](https://cloud.githubusercontent.com/assets/24645147/25000262/9cdc04b2-207b-11e7-84f7-9d7434aa3aca.png)

현재 크롬입니다.
위에 bin 폴더 스크린샷처럼 CHROME_ADDRESS_7 와 달라서 임의로
아래와 같이 해당이미지를 캡쳐했지만, 찾지 못합니다. 
![c](https://cloud.githubusercontent.com/assets/24645147/25000268/a27cf28c-207b-11e7-9066-e29ac6658499.png)

현재 오페라입니다.
위에 bin 폴더 스크린샷처럼 OPERA_ADDRESS_2 와 달라서 임의로
아래와 같이 해당이미지를 캡쳐했지만, 찾지 못합니다. 
특히 오페라 같은 경우 주소에 따라서 이렇게 이미지가 변경되는데, 
어떤것을 캡쳐해야하는지 모르겠습니다; ㅠ_ㅠ
![o](https://cloud.githubusercontent.com/assets/24645147/25000292/ace00d40-207b-11e7-80fb-c91f234bda35.png)

**Comment by ssmmhh** [comment]
https://github.com/naver/guitar/issues/96 문서를 업데이트 하였습니다.
2017/4/14 기준으로 최신 모든 브라우저들에 대한 주소입력 관련 이미지 위치를 추가해 두었습니다. 
필요 이미지들을 다시 캡쳐하여 사용해 보시기 바랍니다. 
모두 정상 작동을 직접 확인하였습니다.

**Comment by ChoiManKi** [comment]
알려주신대로 하니까 정상적으로 잘되네요! 감사합니다!!
즐거운 금요일되세요!
