### ISSUE TITLE
GUITAR는 영어 지원이 안되는지요?

### ISSUE THREAD

**Issue by eastar75** [naver/guitar#346]
스크립트를 한글로 사용하는 것이 너무나 좋습니다.
그런데, 영어로 스크립트 개발 지원은 안되는 것인지요? 
안된다면 혹시 영어 지원 계획이 있으신지 궁금하여 문의 드립니다.

**Comment by ssmmhh** [comment]
아래와 같이 스크립트 자체는 ini 에서 명령어 이름을 추가하셔서 사용하시면 가능합니다.

https://github.com/naver/guitar/issues/224

**Comment by eastar75** [comment]
#224번을 참고하여 INI의 "BrowserRun = 생성|CREATE ~  TagCountGet = 태그개수얻기|GETTAGCOUNT "까지 수정한 내용을 기준으로 korean.lng 파일의 "Command_Click ~ Command_WDNavigateRefresh"까지 수정을 했습니다만 GUITAR.exe 실행 시 "Line 25248 Error : Array variable has incorrect number of subscripts or subscript dimension range exceeded." 에러가 발생하며 실행이 안됩니다.
INI, LNG 파일 수정시 수정하지 말아야 할 Command가 존재 하는지요?

**Comment by ssmmhh** [comment]
korean.lng 파일 수정시 id명과, text 명 사이에는 tab로 되어 있어야 하는데, 혹시 규격에 맞게 하셨는지요?

전체 line 수도 동일해야 하는데, 혹시 실수로 삭제되거 한 부분이 있는지 원본 파일과 비교 확인해 보시기 바랍니다. 

그리고 전체를 수정하지하시고,  1개 정도만 테스트로 영문을 추가한뒤 실행하여 정상작동되는지 먼저 확인해 보시면  에러 원인을 파악하는데 좀더 쉬우실겁니다.

원인을 찾기 어려우시면 문제가 발생된 파일을 전달해 주시면 확인해 드리겠습니다.

**Comment by eastar75** [comment]
답변 감사 드립니다.. 말씀하신 내용처럼 탭으로 되어 있는것은 모두 확인을 했습니다만 동일 현상이 발생을 하네요.. 이상한것은 korean.lng 파일의 "Command_AreaCapture	부분캡쳐" 부터 수정을 하면 에러 현상이 발생하고 바로 위의 "Command_FullScreenWork	전체대상작업|ALLTARGETWORK"까지만 수정을 하면 에러가 발생을 하네요..혹시나 제가 무엇을 잘못했는지.. 검토 좀 부탁 드립니다..

[inilng.zip](https://github.com/naver/guitar/files/953960/inilng.zip)

**Comment by ssmmhh** [comment]
확인해 보니 특정 갯수 이상 변경시 오류가 발생되는 문제가 확인되었습니다.

기존 버전에서 해당 부분만 수정한 버전을 첨부해 드리니, 이 버전으로 작업해 보시기 바랍니다.

[GUITAR_2.0.0.13.zip](https://github.com/naver/guitar/files/954040/GUITAR_2.0.0.13.zip)

**Comment by eastar75** [comment]
너무나 빠른 대응에 감사의 말씀을 드립니다...받아서 바로 테스트해 보도록 하겠습니다..
