### ISSUE TITLE
NOX 프로세스 오류 

### ISSUE THREAD

**Issue by kim-hana** [naver/guitar#347]
NOX로 진행 하는때 어쩔때는 실행이 되고  대부분이  프로세스 실행시 실패가 떨어져서요 ㅠㅠ 

 "$Nox실행=ProcessClose('Nox.exe')" 계산한다.

"$Nox파일=" 설정한다.
"$Nox파일존재=FileExists('C:\Program Files (x86)\Nox\bin\Nox.exe')" 계산한다.
 $Nox파일존재=1 같으면 "$Nox파일=C:\Program Files (x86)\Nox\bin\Nox.exe" 설정한다.

"$Nox파일존재=FileExists('C:\Program Files (x86)\Nox\bin\Nox.exe')" 계산한다..
 $Nox파일존재=1 같으면 "$Nox파일=C:\Program Files (x86)\Nox\bin\Nox.exe" 설정한다.

"$Nox실행=ShellExecute('|$Nox파일|')" 계산한다.

Nox 프로세스선택 한다.
150초 대기한다

![nox](https://cloud.githubusercontent.com/assets/26728730/25259876/9f0862cc-2683-11e7-8416-81935abad567.png)

**Comment by ssmmhh** [comment]
아래와 같이 실행후 5초 정도 뒤에 프로세스 선택을 해 보시기 바랍니다.
그래도 에러가 발생된다면 실제 화면에 해당 프로세스가 실행되지 않았는디 "작업관리자" 등에서 
실행중인지 확인해 보시기 바랍니다. 

"$Nox실행=ShellExecute('|$Nox파일|')" 계산한다.
5초 대기한다.
Nox 프로세스선택 한다.

**Comment by kim-hana** [comment]
감사합니다. 실행 후  대기시간을 주니 정상적으로 잘 작동하네요 .
