### ISSUE TITLE
일반 Application 테스트는 안되는 것인지요?

### ISSUE THREAD

**Issue by eastar75** [naver/guitar#359]
Chrome, IE가 아닌 일반 CS System UI에 대한 테스트를 수행 하고자 합니다만..

특정 이미지를 클릭 하는 경우 하기와 같은 에러 메세지만 나오네요..

명령 실행 실패 : 웹 브라우저가 생성되지 않았습니다.
브라우저 화면 : 

제가 알기로는 좌표와 이미지 기반으로 동작하는 프로그램이기 때문에 사용이 가능할 것으로 판단을 하였습니다.
전체 화면 사이즈로 테스트 중입니다만 해당 창을 인식하도록 별도 작업이 필요한 것인지요?
전체 화면에서 캠쳐한 이미지를 찾지 못하여 문의 드립니다.

답변 부탁 드립니다.
감사합니다.

**Comment by ssmmhh** [comment]
윈도우 응용프로그램에 대한 테스트 지원을 문의하신것 같습니다.

가능합니다. 아래 글을 참조하시고, 해당 글의 설명된 예제를 참고하시기 바랍니다.

https://github.com/naver/guitar/issues/282

**Comment by eastar75** [comment]
빠른 답변에 감사 드립니다.. 알려주신데로 해결 되었습니다..
감사합니다..
