### ISSUE TITLE
테스트 세팅에 관해 질문 있습니다.

### ISSUE THREAD

**Issue by sangmoon** [naver/guitar#363]
guitar 를 사용해 크로스 브라우징 테스트를 하려고 합니다.
ie8,9,10,11,edge, chrome, firefox 을 대상으로 하려고 하는데
컴퓨터가 window10인 관계로 ie8,9,10은 virtualbox를 이용하고 있습니다.

질문1 ) edge 테스트는 불가능한건가요?
질문2) host window에서 테스트를 돌려 virtualbox내 ie로 동작시킬 수는 없는 건가요?
           즉 각각의 virtual 환경에서 guitar를 설치해서 각각 실행 시켜야 하나요?

감사합니다.

**Comment by ssmmhh** [comment]
1. 
edge는 현재 지원하고 있지 않습니다,  때문에 효율적으로 테스트 진행하기는 어렵습니디다만, 일반 어플리케이션 처럼 테스트는 가능합니다.
"프로세스선택" 으로 브라우저가 아닌 일반 어플 처럼 테스트 하시면 됩니다. 
URL 입력같이 기존 GUITAR가 해주는 것들은 자체적으로 별도의 함수형태 스크립트를 만들어서 사용하시면 됩니다. 

2. 
virtual 박스와 메인 머신간의 제어는 지원하지 않고 있습니다. 해당 방식으로 테스느는 어려우며, 각각 가상머신별로 GUITAR를 설치해 사용하셔야 합니다.

**Comment by sangmoon** [comment]
빠른 답변 감사합니다!
