### ISSUE TITLE
부분 대상 작업 관련 좌표 불일치 현상

### ISSUE THREAD

**Issue by eastar75** [naver/guitar#368]
전체 화면에서 실행되는 프로그램의 특정 영역을 캡쳐했을때 보여지는 절대 좌표값과 
부분캡쳐나 부분대상작업을 위해 설정한 좌표값을 동일하게 했는데 캡쳐된 이미지가 한쪽으로 쏠리는 현상이 있습니다.

"290,170,360,260" 해당 죄표의 실제 위치에 대한 이미지와 부분캡쳐로 캡쳐한 이미지가 다릅니다.
실제 화면의 좌표보다 X나 Y축이 이동이 된 상태로 캡쳐 및 부분 대상 영역으로 설정이 됩니다.
실제 영역: 1번(붉은색)
캡쳐 영역 : 2번(푸른색)
![yardarea_](https://user-images.githubusercontent.com/27768291/29600656-2b4e7e52-8812-11e7-9efd-c9cf2bb61272.png)

해결 할 수 있는 방법이 있을런지요?
검토 부탁 드립니다.

**Comment by eastar75** [comment]
상기 작업 목적은 17번 하단의 두번째 박스부터 17-21 사이 블럭의 맨 하단 박스까지
드래그&드롭을 구현하는 중에 이런 저런 방법을 구상하던 중 확인된 내용입니다.....참고 부탁 드립니다.

**Comment by ssmmhh** [comment]
실제 스크립트에서 사용한 좌표를 지정한 방식과 캡쳐한 방식을 정확하게 알려 주셔야 확인이 가능할것 같습니다. 
실제 사용하시는 스크립트 내용과 참고가 되는 이미지를 보내 주시면 확인해 드리겠습니다.

또한 아래와 같이 특정 프로세스에서 부분캡쳐가 정상 작동되는지 왼쪽상단 100x100 영역을 캡쳐하도록 하여
정상캡쳐되는지 확인해 보시기 바랍니다.
--------
xxxx 프로세스선택
"0,0,100,100" 부분캡쳐

**Comment by eastar75** [comment]
감사합니다. 금일 재부팅 후 '캡쳐' 영역 저장 후 동일 좌표로 '부분캡쳐' 명령으로 해보니 동일한 이미지 확인 했습니다.  무엇을 잘못한것인지 모르겠네요..^^;;; 문제가 재발생하면 스크립트와 이미지 첨부하여 다시 문의 드리겠습니다.
감사합니다...
