### ISSUE TITLE
메일 설정하는 부분이 제대로 안되네요. 

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#371]
아래와 같이 메일 설정하는 ini파일을 변경했는데 테스트 메일이 정상적으로 수신이 안됩니다. 
메일기능 관련 도움말 확인하라는 링크는 주소 존재하지 않음으로 뜹니다.
( http://help.naver.com/ops/step2/faq.nhn?)
지원 부탁드립니다. 

[ALARM]
; 각 목록은 "," 로 다중 기록 가능
SMS= False
Email= True
CommandlineModeOnly = True
SMSList=010-0000-0000
EmailList=xxx@navre.com 
EmailImageAttach=True
EmailSummary=True

[EMAIL]
; 네이버메일 SMTP 설정방법 http://help.naver.com/ops/step2/faq.nhn?faqId=4643&faqType=4643&fcatid=12211
SMTPServer = smtp.naver.com
Port = 465
ID = xxxx
Password = xxxx
EmailAddress = xxxx@naver.com
[HTML_TAG]
HighlightDelay=500

**Comment by ssmmhh** [comment]
네이버 메일서비스 도움말 링크가 업데이트 되면서 깨진것 같습니다.

https://help.naver.com/support/search/searchResultAll.nhn?searchText=smtp

위의 검색결과의 글에서 smtp 관련 내용을 확인해 설정해 보시기 바랍니다.
