### ISSUE TITLE
영어로 입력했는데 한글로 쳐집니다.

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#372]
텍스트창에 입력한다 명령어가 안들어서 누른다라는 명령어로 사용중인데,
"jun" 누른다 라고 스크립트를 만들어서 돌리면  입력창에 "jun"이 아니라  "ㅓㅕㅜ"으로 입력이 됩니다.
해결방안 도움 부탁드립니다. 

음..두번째로 문의한 현상은  취소처리했습니다.
윈도우 7 64비트 환경입니다.
영어로 스크립트 입력한 부분이 한글로 인식되는 부분만 확인 바랍니다.

**Comment by ssmmhh** [comment]
사용하시는 테스트 환경을 좀더 자세히 알려주세요

OS 및 브라우저 버전등 그리고 첨부된 파일을 생성한다고 하셨는데요. 어떤것을 얘기하시는지 이해가 되지 않습니다. 자세한 설명 부탁드립니다.
