### ISSUE TITLE
영어 인식안되는 문제

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#373]
텍스트창에 입력한다 명령어가 안들어서 누른다라는 명령어로 사용중인데,
 "jun" 누른다 라고 스크립트를 만들어서 돌리면 입력창에 "jun"이 아니라 "ㅓㅕㅜ"으로 입력이 됩니다.
해결방안 도움 부탁드립니다.

윈도우 7 64비트 환경입니다.

**Comment by jinso84** [comment]
답변 감사합니다. .. url이 오픈이 아닌 시스템이라, url을 알려드릴수는 없을거 같은데. 기타적으로 어떤 환경을 알려드려야 지원을 받을수 있을까요.
동일한 이미지의 입력창이 여러개인 메일 발송에서 기타프로그램를 사용하려고 하고있으며, 메일 발송함수가 아닌 버튼 자동클릭기능을 통해 메일을 보내려고 테스트 중입니다. 
문제가 되는 부분은. 메일 제목은 영어가 잘 입력되는데(누른다로 사용중) , 수신인 리스트및 본문에
영어가 입력이 안되고 한글로 입력이 되는 상황입니다.
스크립트는 대략.
검색창에 "화면점검"를 누른다.    => 메일제목   (영어인식 ok)
"{TAB}" 누른다
검색창에 "jun" 를 누른다.     => 수신인 (영어인식 안됨     jun이 아니라 ㅓㅕㅜ 으로 입력됨  )

인터넷 익스플로러 11프로그램이며, 화면은 엑스플래폼을 사용중입니다.

**Comment by ssmmhh** [comment]
아마도 사용하시는 엑스플랫폼쪽에서 한글 입력 부분에 문제가 있는것 같습니다.
일단 "누른"다는 명령은 위에 설명드린것과 같이 물리키를 누르는 용도로 쓰셔야 합니다. 
영문의 경우 기본 키값이 영문이기 때문에 문제가 없으나, 한글등으로 입력시도시 의도하지 않는 결과가 발생될수 있습니다.

일단 "입력" 명령을 입력되도록 해결하시는것이 가장 좋을것 같은데요.
제가 재현이 할수 있는 환경이 없음으로 한글을 입력가능한 다른 방법을 알려 드리니 아래 방법으로 시도해 보시기 바랍니다.
윈도우의 클립보드에 입력내용을 복사한뒤 ctrl+v 로 붙여넣어 입력하는 방식입니다.


---------

"$클립보드복사=ClipPut ('한글입력')" 계산한뒤 "^v" 누른다.

**Comment by jinso84** [comment]
답변 너무 감사드립니다. 답변드린것과 반대로, 전 영문인식이 안되는 케이스였는데, 주신 코멘트로 정상인식처리되었습니다.  추가로 문의드립니다.
subject 검색창 네모
로 되어있는 칸에 입력하기 위해서 해당 항목을 이미지 처리(Mail_title로 지정) 해서 스크립트를 
=======================
화면에서 Mail_title 을 클릭한다. 
검색창에 "화면점검"를 누른다.
=======================
을 사용했더니 동작을 하기는 하나, 이미지 찾은후 실제 검색창에 입력하게 되기까지 1분 가량이 걸립니다. 몇초 대기라는 스크립트를 쓰지 않았는데, 대기시간이 긴것은 이미지를 제대로 못찾는것 같다는 느낌이 드나, 엄청 느릴뿐 동작이 정상적이기 때문에 수정을 어떤 방식으로 해야할지 모르겠습니다.
도움 부탁드립니다.

**Comment by ssmmhh** [comment]
오래 걸려서 클릭이 된다면 캡쳐시점의 이미지와 현재상태의 이미지가 미세하게 틀려진것 같습니다.

아래 Tip 게시물을 참고해서 

https://github.com/naver/guitar/issues/70

원인을 파악해서 조치하시면 될것 같습니다.
쉽게 하는 방법은 현재 화면에 보여진느 이미지를 추가로 캡쳐에서 "_"를 추가 저장해
사용하시면 됩니다.

**Comment by jinso84** [comment]
네 조치되었습니다. 답변 정말 감사드립니다.
