### ISSUE TITLE
DB연동가능여부 문의드립니다.

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#374]
기타랑 DB를 연동해서 사용가능한지 문의드립니다.
안된다면,,,특정 데이터가 나오는 경우를 메일링하려고 할때, 특정데이터를 이미지화시켜
해당 이미지가 있다면, 메일발송..이런식으로 구현하려고 하는데
스크롤바때문에 전체 이미지 확인이 안되네요
화면아래 스크롤바를 끝까지 내려 원하는 이미지가 있는지 찾는 방법이 있는지 문의드립니다.

**Comment by ssmmhh** [comment]
1. DB연동 기능은 지원하지 않습니다.
다만 파일DB 기능을 사용해서 유사하게 원하시는 작업을 하실수 있습니다.
반복문등으로 파일DB에서 내용을 읽어봐 비교한뒤 원하시는 작업을 하시면 될것 같습니다.
(참고 : 48_파일DB 예제)


2. 화면 스크롤 이슈는 직접 사용할때 처럼 화면을 스크롤 주셔야 합니다. 
관련해서는 다른 글에 내용이 있음으로 "스크롤"로 검색해 보시기 바랍니다.

https://github.com/naver/guitar/issues?utf8=%E2%9C%93&q=%EC%8A%A4%ED%81%AC%EB%A1%A4

**Comment by jinso84** [comment]
답변 감사드립니다. 샘플 스크립트는 사이트에선 47번까지밖에 없던데 48번은 어디서 얻을수 있는지랑,
스크롤이슈의 경우, 참고해주신 URL에선 원하는 내용을 찾을수 없었습니다.
스크롤바를 이미지화하여, 스크롤바를 클릭한다. 라고 스크립트를 짤 경우, 해당이미지가 나올때까지
아래로 당기는 동작과, 끝까지 내리는 동작등은 어떻게 구현해야하는지 문의드립니다.

**Comment by ssmmhh** [comment]
Leave a comment1. 2.0 버전을 설치하시면 최신 샘플 예제들은 기본 포함되었습니다.
https://github.com/naver/guitar/releases


2.
문의하신 스크롤 관련 내용은 아래 TIP 게시물 중간쯤 부분에 있습니다. 


https://github.com/naver/guitar/issues/27

"
회사로고가 없으면 "{PGDN}" 누른다. 회사로고가 없으면 "{PGDN}" 누른다. 회사로고가 없으면 "{PGDN}" 누른다. 회사로고가 없으면 "{PGDN}" 누른다.
회사로고를 클릭한다.
"

**Comment by jinso84** [comment]
친절한 답변 감사드립니다. 버전 업그레이드해서 파일저장..스크립트는 봤는데, 변환데이터를 바로 읽어오지 못해 적용은 못할거 같구요...
두번째 질문이었던 스크롤은...적용해봤으나, 동작이 정상적으로 되지 않았습니다.
[작성 스크립트 예시]
Result_error없으면 Scroll 누른다.
Result_error없으면 Scroll 누른다.
Result_error있으면 "CP_Mail(D)"를 실행한다
 
찾으려는 대상이미지를 Result_error으로 저장하였고, 해당이미지가 보이면 메일발송. 없으면 종료처리하고자 하는 스크립트입니다. (엑스플랫폼)
 Scroll 라는 제목으로 스크롤바를 이미지화처리하여, 누른다. 및 클릭한다 등을 입력해봤으나
해당항목이 동작하지 않았습니다. 클릭한 상태로 아래를 내려야 하는데, 알려주신 샘플의 pgdn을 활용해서 해보려 하였으나 잘 되지 않네요...다시한번 지원 부탁드립니다.

**Comment by ssmmhh** [comment]
자동화를 하기 전에 직접 수동으로 클릭이나 스크롤바 부분을 클릭했을때 작동되는지를 먼저 확인해 보시기 바랍니다.

"Scroll 누른다. " 라는 명령이 잘못되었습니다. 원하시는건 화면이 스크롤 되는것을 원하는데.
사용하신 명령은 키보드에 "Scroll"이라고 누른것 입니다. "누른" 명령은 키보드는 누르는 명령입니다.

자판에 "Scroll" 이라고 쓴다고 해서 화면이 스크롤 되지는 않습니다.

스크롤 하기 위해서는 일반 사람이 하는것 처럼 page down 키를 누르거나, 마우스를 휠을 아래로 돌리거나, 오른에 있는 스크롤 바를 누르거나 여러 가지 방법으로 하실수가 있습니다. 

"pgdn" 이 그중 가장 쉬운 방법인데요.
실제 해당 영역에서 포커스가 있는 상태에서 pgdn 키를 눌러 스크롤이 일어 나는지를 먼저 확인해 보시기 바랍니다.

그리고 pgdn 키를 누르기 전에 항상 해당 스크롤 하고자 하는 영역에 포커를 먼저 이동해야 합니다.
(클릭명령등으로)

예를 들면 브라우저 화면에서 주소창에 커서가 있는데 스크롤 하려고 pgdn을 누르면 주소입력창 내에서만 커서가 움직이는것과 같은 현상이 발생됩니다.

마우스휠 명령이나 키보드 명령 전에는 항상 해당 영역에 포커스를 주시고 하셔야 합니다. (일반 사람이 하는것 처럼)

**Comment by ssmmhh** [comment]
pgdn 과 같이 특수한 키 이름은 guitar -> 도움말 -> autoit 키 목록 메뉴를 참고하시기 바랍니다.
입력에 관련 자세한 내용은 설명서 "6.4	키보드 관련 명령어" 부분을 참고하시기 바랍니다.
예제는 09마우스, 01번 예제등을 참고하시기 바랍니다.

"마우스휠다운" 명령등으로도 스크롤 가능합니다. (단 키입력과 같이 먼저 스크롤 하고자 하는 영역에 포커스를 먼저 이동해 주셔야 합니다.)

**Comment by jinso84** [comment]
설명 너무 감사드립니다. 오류 해결되었습니다. ^^
