### ISSUE TITLE
마우스 휠 관련문의드립니다.

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#375]
해당이미지가 나올때까지 마우스휠다운을 한다. 라는 스크립트를 사용중인데, 화면에 스크롤이 길다보니
마우스휠다운을 한다라는 스크립트를 300개를 써야..끝이 보이는 정도입니다.
페이지 다운은 화면에서 동작하지 않구요. 좀더 빨리 화면을 끝까지 내릴수 있는 기능은 없을까요?

**Comment by ssmmhh** [comment]
사람이 할수 있는것과 동일하게 액션을 취해 주시면 됩니다.

키보드 pndn이 안되면 우측에 있는 마우스로 스크롤바 오른쪽 아래 부분을 클릭해서 스크롤 하시면 될것 같습니다. 

보통 UI라면 end 키라든가, pgdn 키 등 키보드로 스크롤 되어야지 정상인데요. 

이것을 막아 놓은 상태라면 어쩔수 없이 사람이 하는것 처럼 마우스로 계속 원하는 화면이 나올때까지 스크롤을 하셔야 할것 같습니다. 

(가능한 키보드로 스크롤 가능한 방법이 있는지 좀더 알아 보시는게 좋을것 같습니다.)

**Comment by jinso84** [comment]
end 키라든가, pgdn 키는 현재 UI에서 사용불가합니다..그렇다면 마우스로 스크롤 다운하는 방법외에, 마우스로 스크롤바를 찍어서 내리는 방법은 안되나요?
스크롤바를 이미지화시켜서 클릭한뒤 아래바닥에 닿을때까지 내리고 싶은데요. 스크립트로 구현가능한지 문의합니다.
스크롤바를 클릭한다. 끌고 내린다...뭐 이런종류의 스크립트가 있는지 여부입니다.

**Comment by ssmmhh** [comment]
위의 답변처럼 "마우스로 스크롤바 오른쪽 아래 부분을 클릭해서 스크롤 하시면 될것 같습니다." 

사람이 하는것과 같이 동일하게 마우스로 작업하도록 하시면 됩니다. 스크롤 바 하단을 캡쳐하셔서 그분을 클릭하게 하시면 됩니다.
