### ISSUE TITLE
이슈라고 하기엔.

### ISSUE THREAD

**Issue by jinso84** [naver/guitar#382]
이슈창이지만 이슈가 아닌 글을 드립니다.
써포트 창에 댓글을 빨리 달아주신덕에 작은 프로젝트를 잘 마무리했습니다.
하나 하나 이슈를 올리고 답글이 달렸음에도 계속 질문을 했는데, 성의껏 댓글 달아주셔서 정말 큰 도움됐습니다. .
기타 사용시 또 문의사항이 생기면 . 질문 드리겠습니다. 
정말 감사합니다.^--^

**Comment by ssmmhh** [comment]
도움이 되셨다니 다행입니다.^^;
