### ISSUE TITLE
dev.naver.com에 작성되었던 tip은 다시 찾아볼 수 없나요?

### ISSUE THREAD

**Issue by koko8829** [naver/guitar#387]
캡쳐 관련 이슈를 찾아보다가 관련 문서가 dev.naver.com에 있다는 답변을 보았습니다.
https://github.com/naver/guitar/issues/23
해당 주소를 찾아가보니 지금은 접속이 되지 않네요.
http://dev.naver.com/projects/guitar/tip/70655

혹 해당 자료를 찾으려면 어디서 찾아보아야 할까요?

**Comment by ssmmhh** [comment]
팁 게시물은 아래 URL 에서 보실수 있으며,  

(Labels -> Tip)

https://github.com/naver/guitar/labels/Tip

깨진 링크의 게시물은

https://github.com/naver/guitar/issues/70

입니다.

**Comment by koko8829** [comment]
감사합니다. 
궁금한 점도 같이 해결되었네요 ^^
