### ISSUE TITLE
트레이창에서 표시되는 알림(?)을 생성되지 않도록 할 수 있을까요?

### ISSUE THREAD

**Issue by koko8829** [naver/guitar#388]
간단한 작업을 테스트해보고 있습니다.
실제 테스트는 끝나고 결과 리포트까지 보여주었는데
트레이창에서 표시되는 알림은 이제 막 중간 단계를 보여주고 있더군요.
실제 동작에 영향을 끼치는 것은 아닌데 혹 트레이창에서 표시되는 알람(?)을 보이지 않도록 할 수 있을까요?
윈도우 10 환경입니다.
![image](https://user-images.githubusercontent.com/9835224/32312997-fd3ad858-bfe3-11e7-9cbf-fc11ac9bac7c.png)

**Comment by ssmmhh** [comment]
GUITAR.INI 에서 옵션값을 변경해 주시면 됩니다.

TrayToolTip = False

**Comment by koko8829** [comment]
툴 자체에 옵션이 있으리라 생각했습니다.
매뉴얼을 읽어보긴 했는데 놓친 부분이네요.
감사합니다.
