### ISSUE TITLE
INPUT 태그에 커서가 있는 경우는 어떻게 이미지를 비교하나요?

### ISSUE THREAD

**Issue by koko8829** [naver/guitar#389]
첫번째 입력상자에 포커스가 있는 경우 커서가 깜빡이면서
이미지를 캡쳐한 것과 GUITAR에서 처리하는 이미지가 다른 경우가 있습니다. 
이런 경우에는 어떻게 처리하면 되나요?
- 비교할 이미지
![image](https://user-images.githubusercontent.com/9835224/32315235-bc39c89a-bfee-11e7-8598-1c29cb2b73d6.png)
- 테스트 시 캡쳐 이미지
![image](https://user-images.githubusercontent.com/9835224/32315298-e8df9aaa-bfee-11e7-9fa3-5ad3f0f4c023.png)

**Comment by ssmmhh** [comment]
다른곳으로 마우스나 키보드 포커스를 이동하시면 됩니다.
아래와 같이 tab 키를 누르거나, 다른 액션이 없는 빈 이미지등을 클릭하시면 포커스가 이동 됩니다.
혹은 커서가 있는 부분을 빼고 캡쳐하셔도 됩니다.
--------
"{TAB}" 누른다

**Comment by koko8829** [comment]
포커스를 어떻게 옮길 수 있는지를 못찾았는데
의외로 간단한 방법이었네요 ㅠㅠ
DELETE 키 입력하는 스크립트를 조금 전에 썼는데 TAB을 생각하지 못했습니다 ㅠㅠ
감사합니다.
