### ISSUE TITLE
이미지 캡쳐 영역 관련 문의

### ISSUE THREAD

**Issue by stegano** [naver/guitar#429]
Win10에서 이미지 캡쳐시 지정영역이 아닌 좌상단 특정 영역이 캡쳐되는것 같은데 혹시 해결 방법이 있을까요?

**Comment by ssmmhh** [comment]
https://github.com/naver/guitar/issues/349 확인해 보시기 바랍니다.

**Comment by stegano** [comment]
감사합니다~ 해결되었습니다 :D
