### ISSUE TITLE
특정 조건일때 반복조건을 사용할 수 있나요?

### ISSUE THREAD

**Issue by ejyoo93** [naver/guitar#443]
안녕하세용. 반복조건에 대해 질문을 드리고자 합니다.

특정 조건일 때 반복하거나,
특정 조건일 때 반복하던 것을 중지하고 테스트를 완료하고자 합니다.
.
.
사용 경우는 이러합니다.
'Lock상태문서' 가 있을 시 'A' 라는 작업을 반복적으로 수행하고,
없으면 테스트 결과는 성공한다.

위의 조건대로 사용을 하고 싶은겁니다.ㅠㅠ
.
.
보통 While 문 처럼..
Lock 상태문서가 존재하는가 ? 여부만 판단해서 
Y 면 A 작업
F 면 종료
식으로 쓰고 싶은데요.. 혹시 방법이 있을까요?ㅠㅠㅠㅠㅠㅠ

**Comment by ssmmhh** [comment]
반복을 활용하시면 가능합니다.


```
$i=1 설정 $i=1000 반복 {
	
	$결과=False 설정

	Lock 있으면 $결과=True 설정
		
	$결과=True 같으면 A.TXT 실행한다.

	$결과=False 같으면 $i=101 설정한다.

	1초 대기한다.
}
```

참고 : https://github.com/naver/guitar/issues/241

**Comment by ejyoo93** [comment]
아 이런 방법이 있었군요! 정말 감사합니다 좋은하루되세요!
