### ISSUE TITLE
텍스트 입력 시 변수와 텍스트를 연속으로 사용하는 방법

### ISSUE THREAD

**Issue by ejyoo93** [naver/guitar#446]
안녕하세요!! GUITAR 툴을 흥미롭게 정말 잘 쓰고있습니다 ㅎㅎ

**질문**
텍스트 입력 시 변수와 텍스트를 연속으로 사용하는 방법이 있나요?

반복적으로 새로운 계정을 생성하고자 하는데요
test1, test2, test3, test4, ..., test100 이런식으로 사용합니다.
딱히 방법이 생각나지 않아서

1  .  $계정생성횟수=1 설정한다. $계정생성횟수=500 반복한다{
2  .  전체대상작업으로, UserId입력란을 클릭한다.
3  .  전체대상작업으로, Text상자에 "test"를 입력한다.
4  .  전체대상작업으로, Text상자에 $계정생성횟수를 입력한다.
5  .   }

이런식으로 사용하고 있습니다.
3, 4번을 한줄로 사용할 수 있는 방법이 있을까요
"nsetec"+$계정생성횟수 처럼요!

**Comment by jojo6677** [comment]
3 . 전체대상작업으로, Text상자에 "test|$계정생성횟수|"를 입력한다.

동작하는지 확인은 안해봤지만 3, 4번을 한 줄로 위처럼 할 수 있을 것 같네요. 
저도 도움 받는 입장이지만 아는 범위 내에서 공유합니다.

**Comment by ejyoo93** [comment]
jojo6677 님 감사합니다.

텍스트랑 변수랑 같이 쓰려면 "|" 를 쓰면되는군요!
해결되었습니다.
