### ISSUE TITLE
Internet Explorer 

### ISSUE THREAD

**Issue by jeongjeongguk** [naver/guitar#451]
안녕하세요.  

누구나 쉽게 사용할 수 있는 툴 guitar를 항상 잘 쓰고 있습니다. 

Guitar를 사용하여, 전임자가 작업해놓은 Guitar 텍스트파일을 관리중에,
guitar로 실행한 IE에서만 정상동작이 안되고,
직접 실행한 IE에서는 정상동작이 되고 있어서요.

혹시 guitar로 실행한 IE에서는, 따로 캐시하는 부분이 있는지 해서요.

따로 캐시하는 부분이 있다면, 매번 테스트 종료시마다 해당부분을 지우는 방법이 있을까요?

[ 사용환경 ]
OS : windows server 2008
IE : ver. 11

[ 현재 사용중인 상태 ]
IE 에 설치된 toolbar application 기능 테스트 진행 > 성공/실패 메일 모니터링.

[ 문의 내용 ]
- 스크립트 동작순서
1. Guitar 실행전, IE 및 IE에 설치된 toolbar 의 process 강제종료
2. IE 에 설치된 toolbar application DB를 toolbar 서버로부터 직접 갱신받음.
> Guitar 로 실행한, IE에서는 갱신이전의 DB 로 toolbar 기능 동작함.
> 직접 실행한, IE에서는 갱신된 DB로 toolbar 기능 동작함.
>> **Guitar 로 실행할때에도 직접 실행한것처럼, 갱신된 DB를 참조하게끔 할려면 추가 설정이 필요한지요?**

**Comment by ssmmhh** [comment]
GUITAR가 생성한 IE의 어떠한 권한 문제등으로 인해 제대로 툴바가 작동되지 않는다는 말씀이신것 같습니다.
아래와 같이 스크립트를 작성하시면 기본 IE대신 스크립트에서 다른 방식으로 만든 IE를 대상으로 작업하실수 있습니다.
주요한 핵심 부분은 

"$IE실행=run('C:\Program Files\Internet Explorer\iexplore.exe')" 계산한다.

입니다.

이것과 같이 외부에서 IE를 실행하도록 한뒤 해당 IE로 작업을 수행하시도록 한번 시도해 보시기 바랍니다. 

-------
```

;IE 생성후 종료
IE 생성
"$IE종료=processclose('iexplore.exe')" 계산한다.

;별도로 IE 생성후, 이미지로 대상을 선택
"$IE실행=run('C:\Program Files\Internet Explorer\iexplore.exe')" 계산한다.
IE기본화면 선택 

; 기능 수행
www.google.com 접속

```

**Comment by jeongjeongguk** [comment]
@ssmmhh sample 과 함께 설명 감사드립니다~!
