### ISSUE TITLE
녹스 플레이어 화면을 잘못 잡습니다.

### ISSUE THREAD

**Issue by DonggleKim** [naver/guitar#454]
네 녹스 안을 잡아야하는데
![화면잘못잡힘](https://user-images.githubusercontent.com/35844814/67115207-a43b5700-f218-11e9-933d-a4cd26561017.PNG)

이걸 잡네요..

![화면잘못잡힘_상세](https://user-images.githubusercontent.com/35844814/67115218-aa313800-f218-11e9-9bbe-c5b38be31f5a.PNG)

상세 내용입니다.

부탁드립니다 ㅠㅠ

**Comment by ssmmhh** [comment]
내부적으로 프로세스가 여러개 생성되어 이러한 현상이 발생될 수 있습니다.
이런경우 프로세스선택다음에 "선택" 명령을 추가하여 명확하게 화면이 표시되는 프로세스로를 지정한뒤 사용하시면 됩니다.

아래 유사 글들의 답변을 확인후 시도해 보시기 바랍니다.

https://github.com/naver/guitar/issues/336

https://github.com/naver/guitar/issues/386

**Comment by DonggleKim** [comment]
안녕하세요, 답변 감사합니다. 저럴 경우 녹스를 전체화면이 아닌 작은 화면으로 만들어주거나,
녹스 내 이미지를 잡아 아이콘 선택을 두번 입력하면 자연스럽게 넘어갔습니다.
자동화 툴 잘 사용했습니다. 감사합니다!
-----Original Message-----
